### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Yanchik07** [Shunskiy/pet-projects#1]
**ID 0001a**
При написании большого текста без пробелов убегает кнопка вправо "**Удалить**" и не дает удалить саму задачу на главной странице http://localhost:3000/todo
![image](https://user-images.githubusercontent.com/87774579/134201572-7fe06587-f590-4686-a955-8ab5e5861e74.png)

**Steps:**

1. Зайти на сайт
2. В поле ввода ввести большое количество символов 
3. Нажать кнопку "Добавить задачу"
 
**Expected result**
Кнопка остается на месте и не мешает чтению текста

**Result**
Кнопка съезжает вправо и не возможно удалить задачу 

**Bug severity**
Critical S2

**Priority** High 

**Status Bug**
work

**Comment by Shunskiy** [comment]
Nice car btw

**Comment by Shunskiy** [comment]
To check, you need to write the following in the directory with the project in the terminal:
```
git pull
git checkout bugfix/todo-word-break
npm run start
```
Also, you can check pull request as a reference for your issue #2 to see changes in code

CC @Yanchik07
